services:
  database:
    image: postgres:15.2
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file: .env
    ports:
      - 5173:5173
    networks:
      - app_network

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    env_file: .env
    environment:
      - 8080:8080
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
